# US_CITY_STRUCTURE = {

#     "AL": {"name": "Alabama", "regions": [
#         {"code": "auburn", "name": "Auburn"},
#         {"code": "bham", "name": "Birmingham"},
#         {"code": "dothan", "name": "Dothan"},
#         {"code": "shoals", "name": "The Shoals"},
#         {"code": "gadsden", "name": "Gadsden"},
#         {"code": "huntsville", "name": "Huntsville"},
#         {"code": "mobile", "name": "Mobile"},
#         {"code": "montgomery", "name": "Montgomery"},
#         {"code": "tuscaloosa", "name": "Tuscaloosa"},
#     ]},

#     "AK": {"name": "Alaska", "regions": [
#         {"code": "anchorage", "name": "Anchorage"},
#         {"code": "fairbanks", "name": "Fairbanks"},
#         {"code": "kenai", "name": "Kenai Peninsula"},
#         {"code": "juneau", "name": "Juneau"},
#     ]},

#     "AZ": {"name": "Arizona", "regions": [
#         {"code": "flagstaff", "name": "Flagstaff"},
#         {"code": "mohave", "name": "Mohave County"},
#         {"code": "phoenix", "name": "Phoenix"},
#         {"code": "prescott", "name": "Prescott"},
#         {"code": "showlow", "name": "Show Low"},
#         {"code": "sierravista", "name": "Sierra Vista"},
#         {"code": "tucson", "name": "Tucson"},
#         {"code": "yuma", "name": "Yuma"},
#     ]},

#     "AR": {"name": "Arkansas", "regions": [
#         {"code": "fayar", "name": "Fayetteville"},
#         {"code": "fortsmith", "name": "Fort Smith"},
#         {"code": "jonesboro", "name": "Jonesboro"},
#         {"code": "littlerock", "name": "Little Rock"},
#         {"code": "texarkana", "name": "Texarkana"},
#     ]},

#     "CA": {"name": "California", "regions": [
#         {"code": "bakersfield", "name": "Bakersfield"},
#         {"code": "chico", "name": "Chico"},
#         {"code": "fresno", "name": "Fresno"},
#         {"code": "goldcountry", "name": "Gold Country"},
#         {"code": "hanford", "name": "Hanford"},
#         {"code": "humboldt", "name": "Humboldt County"},
#         {"code": "imperial", "name": "Imperial County"},
#         {"code": "inlandempire", "name": "Inland Empire"},
#         {"code": "losangeles", "name": "Los Angeles"},
#         {"code": "mendocino", "name": "Mendocino County"},
#         {"code": "merced", "name": "Merced"},
#         {"code": "modesto", "name": "Modesto"},
#         {"code": "monterey", "name": "Monterey"},
#         {"code": "orangecounty", "name": "Orange County"},
#         {"code": "palmsprings", "name": "Palm Springs"},
#         {"code": "redding", "name": "Redding"},
#         {"code": "sacramento", "name": "Sacramento"},
#         {"code": "sandiego", "name": "San Diego"},
#         {"code": "sfbay", "name": "San Francisco Bay Area"},
#         {"code": "slo", "name": "San Luis Obispo"},
#         {"code": "santabarbara", "name": "Santa Barbara"},
#         {"code": "santamaria", "name": "Santa Maria"},
#         {"code": "stockton", "name": "Stockton"},
#         {"code": "susanville", "name": "Susanville"},
#         {"code": "ventura", "name": "Ventura"},
#         {"code": "visalia", "name": "Visalia"},
#         {"code": "yubasutter", "name": "Yuba-Sutter"},
#     ]},

#     "CO": {"name": "Colorado", "regions": [
#         {"code": "boulder", "name": "Boulder"},
#         {"code": "coloradosprings", "name": "Colorado Springs"},
#         {"code": "denver", "name": "Denver"},
#         {"code": "eastco", "name": "Eastern Colorado"},
#         {"code": "fortcollins", "name": "Fort Collins"},
#         {"code": "rockies", "name": "Rockies"},
#         {"code": "pueblo", "name": "Pueblo"},
#         {"code": "westslope", "name": "Western Slope"},
#     ]},

#     "CT": {"name": "Connecticut", "regions": [
#         {"code": "newlondon", "name": "New London"},
#         {"code": "hartford", "name": "Hartford"},
#         {"code": "newhaven", "name": "New Haven"},
#     ]},

#     "DE": {"name": "Delaware", "regions": [
#         {"code": "delaware", "name": "Delaware"},
#     ]},

#     "FL": {"name": "Florida", "regions": [
#         {"code": "daytona", "name": "Daytona Beach"},
#         {"code": "fortlauderdale", "name": "Fort Lauderdale"},
#         {"code": "fortmyers", "name": "Fort Myers"},
#         {"code": "gainesville", "name": "Gainesville"},
#         {"code": "heartland", "name": "Heartland"},
#         {"code": "jacksonville", "name": "Jacksonville"},
#         {"code": "keys", "name": "Florida Keys"},
#         {"code": "lakeland", "name": "Lakeland"},
#         {"code": "miami", "name": "Miami"},
#         {"code": "ocala", "name": "Ocala"},
#         {"code": "orlando", "name": "Orlando"},
#         {"code": "panamacity", "name": "Panama City"},
#         {"code": "pensacola", "name": "Pensacola"},
#         {"code": "sarasota", "name": "Sarasota"},
#         {"code": "spacecoast", "name": "Space Coast"},
#         {"code": "staugustine", "name": "St. Augustine"},
#         {"code": "tallahassee", "name": "Tallahassee"},
#         {"code": "tampa", "name": "Tampa"},
#         {"code": "treasurecoast", "name": "Treasure Coast"},
#     ]},

#     "GA": {"name": "Georgia", "regions": [
#         {"code": "albanyga", "name": "Albany"},
#         {"code": "athensga", "name": "Athens"},
#         {"code": "atlanta", "name": "Atlanta"},
#         {"code": "augusta", "name": "Augusta"},
#         {"code": "brunswick", "name": "Brunswick"},
#         {"code": "columbusga", "name": "Columbus"},
#         {"code": "macon", "name": "Macon"},
#         {"code": "nwga", "name": "Northwest Georgia"},
#         {"code": "savannah", "name": "Savannah"},
#         {"code": "statesboro", "name": "Statesboro"},
#         {"code": "valdosta", "name": "Valdosta"},
#         {"code": "warnerrobins", "name": "Warner Robins"},
#     ]},

#     "HI": {"name": "Hawaii", "regions": [
#         {"code": "honolulu", "name": "Honolulu"},
#     ]},

#     "ID": {"name": "Idaho", "regions": [
#         {"code": "boise", "name": "Boise"},
#         {"code": "eastidaho", "name": "East Idaho"},
#         {"code": "lewiston", "name": "Lewiston"},
#         {"code": "twinfalls", "name": "Twin Falls"},
#     ]},

#     "IL": {"name": "Illinois", "regions": [
#         {"code": "bn", "name": "Bloomington-Normal"},
#         {"code": "chambana", "name": "Champaign-Urbana"},
#         {"code": "chicago", "name": "Chicago"},
#         {"code": "decatur", "name": "Decatur"},
#         {"code": "lasalle", "name": "La Salle"},
#         {"code": "mattoon", "name": "Mattoon"},
#         {"code": "peoria", "name": "Peoria"},
#         {"code": "rockford", "name": "Rockford"},
#         {"code": "carbondale", "name": "Carbondale"},
#         {"code": "quincy", "name": "Quincy"},
#     ]},

#     "IN": {"name": "Indiana", "regions": [
#         {"code": "bloomington", "name": "Bloomington"},
#         {"code": "evansville", "name": "Evansville"},
#         {"code": "fortwayne", "name": "Fort Wayne"},
#         {"code": "indianapolis", "name": "Indianapolis"},
#         {"code": "kokomo", "name": "Kokomo"},
#         {"code": "muncie", "name": "Muncie"},
#         {"code": "richmondin", "name": "Richmond"},
#         {"code": "southbend", "name": "South Bend"},
#         {"code": "terrehaute", "name": "Terre Haute"},
#     ]},

#     "IA": {"name": "Iowa", "regions": [
#         {"code": "ames", "name": "Ames"},
#         {"code": "cedarrapids", "name": "Cedar Rapids"},
#         {"code": "desmoines", "name": "Des Moines"},
#         {"code": "dubuque", "name": "Dubuque"},
#         {"code": "fortdodge", "name": "Fort Dodge"},
#         {"code": "iowacity", "name": "Iowa City"},
#         {"code": "masoncity", "name": "Mason City"},
#         {"code": "quadcities", "name": "Quad Cities"},
#         {"code": "siouxcity", "name": "Sioux City"},
#         {"code": "waterloo", "name": "Waterloo"},
#     ]},

#     "KS": {"name": "Kansas", "regions": [
#         {"code": "lawrence", "name": "Lawrence"},
#         {"code": "ksu", "name": "Manhattan / KSU"},
#         {"code": "nwks", "name": "Northwest Kansas"},
#         {"code": "salina", "name": "Salina"},
#         {"code": "seks", "name": "Southeast Kansas"},
#         {"code": "swks", "name": "Southwest Kansas"},
#         {"code": "topeka", "name": "Topeka"},
#         {"code": "wichita", "name": "Wichita"},
#     ]},

#     "KY": {"name": "Kentucky", "regions": [
#         {"code": "bgky", "name": "Bowling Green"},
#         {"code": "eastky", "name": "Eastern Kentucky"},
#         {"code": "lexington", "name": "Lexington"},
#         {"code": "louisville", "name": "Louisville"},
#         {"code": "owensboro", "name": "Owensboro"},
#         {"code": "westky", "name": "Western Kentucky"},
#     ]},

#     "LA": {"name": "Louisiana", "regions": [
#         {"code": "batonrouge", "name": "Baton Rouge"},
#         {"code": "cenla", "name": "Central Louisiana"},
#         {"code": "houma", "name": "Houma"},
#         {"code": "lafayette", "name": "Lafayette"},
#         {"code": "lakecharles", "name": "Lake Charles"},
#         {"code": "monroe", "name": "Monroe"},
#         {"code": "neworleans", "name": "New Orleans"},
#         {"code": "shreveport", "name": "Shreveport"},
#     ]},

#     "ME": {"name": "Maine", "regions": [
#         {"code": "maine", "name": "Maine"},
#     ]},

#     "MD": {"name": "Maryland", "regions": [
#         {"code": "annapolis", "name": "Annapolis"},
#         {"code": "baltimore", "name": "Baltimore"},
#         {"code": "easternshore", "name": "Eastern Shore"},
#         {"code": "frederick", "name": "Frederick"},
#         {"code": "smd", "name": "Southern Maryland"},
#     ]},

#     "MA": {"name": "Massachusetts", "regions": [
#         {"code": "boston", "name": "Boston"},
#         {"code": "capecod", "name": "Cape Cod"},
#         {"code": "southcoast", "name": "South Coast"},
#         {"code": "worcester", "name": "Worcester"},
#     ]},

#     "MI": {"name": "Michigan", "regions": [
#         {"code": "annarbor", "name": "Ann Arbor"},
#         {"code": "battlecreek", "name": "Battle Creek"},
#         {"code": "centralmich", "name": "Central Michigan"},
#         {"code": "detroit", "name": "Detroit"},
#         {"code": "flint", "name": "Flint"},
#         {"code": "grandrapids", "name": "Grand Rapids"},
#         {"code": "holland", "name": "Holland"},
#         {"code": "jxn", "name": "Jackson"},
#         {"code": "kalamazoo", "name": "Kalamazoo"},
#         {"code": "lansing", "name": "Lansing"},
#         {"code": "monroemi", "name": "Monroe"},
#         {"code": "muskegon", "name": "Muskegon"},
#         {"code": "nmi", "name": "Northern Michigan"},
#         {"code": "porthuron", "name": "Port Huron"},
#         {"code": "saginaw", "name": "Saginaw"},
#         {"code": "swmi", "name": "Southwest Michigan"},
#         {"code": "thumb", "name": "The Thumb"},
#     ]},

#     "MN": {"name": "Minnesota", "regions": [
#         {"code": "bemidji", "name": "Bemidji"},
#         {"code": "brainerd", "name": "Brainerd"},
#         {"code": "duluth", "name": "Duluth"},
#         {"code": "mankato", "name": "Mankato"},
#         {"code": "minneapolis", "name": "Minneapolis / St. Paul"},
#         {"code": "rmn", "name": "Rochester"},
#         {"code": "stcloud", "name": "St. Cloud"},
#     ]},

#     "MS": {"name": "Mississippi", "regions": [
#         {"code": "gulfport", "name": "Gulfport / Biloxi"},
#         {"code": "hattiesburg", "name": "Hattiesburg"},
#         {"code": "jackson", "name": "Jackson"},
#         {"code": "meridian", "name": "Meridian"},
#         {"code": "northmiss", "name": "North Mississippi"},
#         {"code": "southmiss", "name": "South Mississippi"},
#     ]},

#     "MO": {"name": "Missouri", "regions": [
#         {"code": "columbiamo", "name": "Columbia"},
#         {"code": "joplin", "name": "Joplin"},
#         {"code": "kansascity", "name": "Kansas City"},
#         {"code": "kirksville", "name": "Kirksville"},
#         {"code": "loz", "name": "Lake of the Ozarks"},
#         {"code": "semo", "name": "Southeast Missouri"},
#         {"code": "springfield", "name": "Springfield"},
#         {"code": "stjoseph", "name": "St. Joseph"},
#         {"code": "stlouis", "name": "St. Louis"},
#     ]},

#     "MT": {"name": "Montana", "regions": [
#         {"code": "billings", "name": "Billings"},
#         {"code": "bozeman", "name": "Bozeman"},
#         {"code": "butte", "name": "Butte"},
#         {"code": "greatfalls", "name": "Great Falls"},
#         {"code": "helena", "name": "Helena"},
#         {"code": "kalispell", "name": "Kalispell"},
#         {"code": "missoula", "name": "Missoula"},
#     ]},

#     "NE": {"name": "Nebraska", "regions": [
#         {"code": "grandisland", "name": "Grand Island"},
#         {"code": "lincoln", "name": "Lincoln"},
#         {"code": "northplatte", "name": "North Platte"},
#         {"code": "omaha", "name": "Omaha"},
#         {"code": "scottsbluff", "name": "Scottsbluff"},
#     ]},

#     "NV": {"name": "Nevada", "regions": [
#         {"code": "elko", "name": "Elko"},
#         {"code": "lasvegas", "name": "Las Vegas"},
#         {"code": "reno", "name": "Reno"},
#     ]},

#     "NH": {"name": "New Hampshire", "regions": [
#         {"code": "nh", "name": "New Hampshire"},
#     ]},

#     "NJ": {"name": "New Jersey", "regions": [
#         {"code": "cnj", "name": "Central NJ"},
#         {"code": "jerseyshore", "name": "Jersey Shore"},
#         {"code": "newjersey", "name": "North NJ"},
#         {"code": "southjersey", "name": "South NJ"},
#     ]},

#     "NM": {"name": "New Mexico", "regions": [
#         {"code": "albuquerque", "name": "Albuquerque"},
#         {"code": "clovis", "name": "Clovis"},
#         {"code": "farmington", "name": "Farmington"},
#         {"code": "lascruces", "name": "Las Cruces"},
#         {"code": "roswell", "name": "Roswell"},
#         {"code": "santafe", "name": "Santa Fe"},
#     ]},

#     "NY": {"name": "New York", "regions": [
#         {"code": "albany", "name": "Albany"},
#         {"code": "binghamton", "name": "Binghamton"},
#         {"code": "buffalo", "name": "Buffalo"},
#         {"code": "catskills", "name": "Catskills"},
#         {"code": "chautauqua", "name": "Chautauqua"},
#         {"code": "elmira", "name": "Elmira"},
#         {"code": "fingerlakes", "name": "Finger Lakes"},
#         {"code": "glensfalls", "name": "Glens Falls"},
#         {"code": "hudsonvalley", "name": "Hudson Valley"},
#         {"code": "ithaca", "name": "Ithaca"},
#         {"code": "longisland", "name": "Long Island"},
#         {"code": "newyork", "name": "New York City"},
#         {"code": "oneonta", "name": "Oneonta"},
#         {"code": "plattsburgh", "name": "Plattsburgh"},
#         {"code": "potsdam", "name": "Potsdam"},
#         {"code": "rochester", "name": "Rochester"},
#         {"code": "syracuse", "name": "Syracuse"},
#         {"code": "utica", "name": "Utica"},
#         {"code": "watertown", "name": "Watertown"},
#     ]},

#     "NC": {"name": "North Carolina", "regions": [
#         {"code": "asheville", "name": "Asheville"},
#         {"code": "boone", "name": "Boone"},
#         {"code": "charlotte", "name": "Charlotte"},
#         {"code": "eastnc", "name": "Eastern NC"},
#         {"code": "fayetteville", "name": "Fayetteville"},
#         {"code": "greensboro", "name": "Greensboro"},
#         {"code": "hickory", "name": "Hickory"},
#         {"code": "onslow", "name": "Jacksonville / Onslow"},
#         {"code": "outerbanks", "name": "Outer Banks"},
#         {"code": "raleigh", "name": "Raleigh"},
#         {"code": "wilmington", "name": "Wilmington"},
#         {"code": "winstonsalem", "name": "Winston-Salem"},
#     ]},

#     "ND": {"name": "North Dakota", "regions": [
#         {"code": "bismarck", "name": "Bismarck"},
#         {"code": "fargo", "name": "Fargo"},
#         {"code": "grandforks", "name": "Grand Forks"},
#         {"code": "nd", "name": "North Dakota (Other)"},
#     ]},

#     "OH": {"name": "Ohio", "regions": [
#         {"code": "akroncanton", "name": "Akron / Canton"},
#         {"code": "ashtabula", "name": "Ashtabula"},
#         {"code": "athensohio", "name": "Athens"},
#         {"code": "chillicothe", "name": "Chillicothe"},
#         {"code": "cincinnati", "name": "Cincinnati"},
#         {"code": "cleveland", "name": "Cleveland"},
#         {"code": "columbus", "name": "Columbus"},
#         {"code": "dayton", "name": "Dayton"},
#         {"code": "limaohio", "name": "Lima"},
#         {"code": "mansfield", "name": "Mansfield"},
#         {"code": "sandusky", "name": "Sandusky"},
#         {"code": "toledo", "name": "Toledo"},
#         {"code": "tuscarawas", "name": "Tuscarawas County"},
#         {"code": "youngstown", "name": "Youngstown"},
#         {"code": "zanesville", "name": "Zanesville"},
#     ]},

#     "OK": {"name": "Oklahoma", "regions": [
#         {"code": "lawton", "name": "Lawton"},
#         {"code": "enid", "name": "Enid"},
#         {"code": "oklahomacity", "name": "Oklahoma City"},
#         {"code": "stillwater", "name": "Stillwater"},
#         {"code": "tulsa", "name": "Tulsa"},
#     ]},

#     "OR": {"name": "Oregon", "regions": [
#         {"code": "bend", "name": "Bend"},
#         {"code": "corvallis", "name": "Corvallis"},
#         {"code": "eastoregon", "name": "Eastern Oregon"},
#         {"code": "eugene", "name": "Eugene"},
#         {"code": "klamath", "name": "Klamath Falls"},
#         {"code": "medford", "name": "Medford"},
#         {"code": "oregoncoast", "name": "Oregon Coast"},
#         {"code": "portland", "name": "Portland"},
#         {"code": "roseburg", "name": "Roseburg"},
#         {"code": "salem", "name": "Salem"},
#     ]},

#     "PA": {"name": "Pennsylvania", "regions": [
#         {"code": "altoona", "name": "Altoona"},
#         {"code": "chambersburg", "name": "Chambersburg"},
#         {"code": "erie", "name": "Erie"},
#         {"code": "harrisburg", "name": "Harrisburg"},
#         {"code": "lancaster", "name": "Lancaster"},
#         {"code": "allentown", "name": "Lehigh Valley"},
#         {"code": "meadville", "name": "Meadville"},
#         {"code": "philadelphia", "name": "Philadelphia"},
#         {"code": "pittsburgh", "name": "Pittsburgh"},
#         {"code": "poconos", "name": "Poconos"},
#         {"code": "reading", "name": "Reading"},
#         {"code": "scranton", "name": "Scranton"},
#         {"code": "pennstate", "name": "State College"},
#         {"code": "williamsport", "name": "Williamsport"},
#         {"code": "york", "name": "York"},
#     ]},

#     "RI": {"name": "Rhode Island", "regions": [
#         {"code": "providence", "name": "Providence"},
#     ]},

#     "SC": {"name": "South Carolina", "regions": [
#         {"code": "charleston", "name": "Charleston"},
#         {"code": "columbia", "name": "Columbia"},
#         {"code": "florencesc", "name": "Florence"},
#         {"code": "greenville", "name": "Greenville"},
#         {"code": "hiltonhead", "name": "Hilton Head"},
#         {"code": "myrtlebeach", "name": "Myrtle Beach"},
#     ]},

#     "SD": {"name": "South Dakota", "regions": [
#         {"code": "nesd", "name": "Northeast SD"},
#         {"code": "rapidcity", "name": "Rapid City"},
#         {"code": "siouxfalls", "name": "Sioux Falls"},
#         {"code": "sd", "name": "South Dakota (Other)"},
#     ]},

#     "TN": {"name": "Tennessee", "regions": [
#         {"code": "chattanooga", "name": "Chattanooga"},
#         {"code": "clarksville", "name": "Clarksville"},
#         {"code": "cookeville", "name": "Cookeville"},
#         {"code": "jackson", "name": "Jackson"},
#         {"code": "knoxville", "name": "Knoxville"},
#         {"code": "memphis", "name": "Memphis"},
#         {"code": "nashville", "name": "Nashville"},
#         {"code": "tricities", "name": "Tri-Cities"},
#     ]},

#     "TX": {"name": "Texas", "regions": []},

#     "UT": {"name": "Utah", "regions": []},

#     "VT": {"name": "Vermont", "regions": []},

#     "VA": {"name": "Virginia", "regions": []},

#     "WA": {"name": "Washington", "regions": []},

#     "WV": {"name": "West Virginia", "regions": [
#         {"code": "charlestonwv", "name": "Charleston"},
#         {"code": "martinsburg", "name": "Eastern Panhandle"},
#         {"code": "huntington", "name": "Huntington"},
#         {"code": "parkersburg", "name": "Parkersburg"},
#     ]},

#     "WI": {"name": "Wisconsin", "regions": []},

#     "WY": {"name": "Wyoming", "regions": []},

# }




US_CITY_STRUCTURE = {

    "Alabama": {"regions": [
        {"code": "auburn", "name": "Auburn"},
        {"code": "bham", "name": "Birmingham"},
        {"code": "dothan", "name": "Dothan"},
        {"code": "shoals", "name": "The Shoals"},
        {"code": "gadsden", "name": "Gadsden"},
        {"code": "huntsville", "name": "Huntsville"},
        {"code": "mobile", "name": "Mobile"},
        {"code": "montgomery", "name": "Montgomery"},
        {"code": "tuscaloosa", "name": "Tuscaloosa"},
    ]},
    "Alaska": {"regions": [
        {"code": "anchorage", "name": "Anchorage"},
        {"code": "fairbanks", "name": "Fairbanks"},
        {"code": "kenai", "name": "Kenai Peninsula"},
        {"code": "juneau", "name": "Juneau"},
    ]},
    "Arizona": {"regions": [
        {"code": "flagstaff", "name": "Flagstaff"},
        {"code": "mohave", "name": "Mohave County"},
        {"code": "phoenix", "name": "Phoenix"},
        {"code": "prescott", "name": "Prescott"},
        {"code": "showlow", "name": "Show Low"},
        {"code": "sierravista", "name": "Sierra Vista"},
        {"code": "tucson", "name": "Tucson"},
        {"code": "yuma", "name": "Yuma"},
    ]},
    "Arkansas": {"regions": [
        {"code": "fayar", "name": "Fayetteville"},
        {"code": "fortsmith", "name": "Fort Smith"},
        {"code": "jonesboro", "name": "Jonesboro"},
        {"code": "littlerock", "name": "Little Rock"},
        {"code": "texarkana", "name": "Texarkana"},
    ]},
    "California": {"regions": [
        {"code": "bakersfield", "name": "Bakersfield"},
        {"code": "chico", "name": "Chico"},
        {"code": "fresno", "name": "Fresno"},
        {"code": "goldcountry", "name": "Gold Country"},
        {"code": "hanford", "name": "Hanford"},
        {"code": "humboldt", "name": "Humboldt County"},
        {"code": "imperial", "name": "Imperial County"},
        {"code": "inlandempire", "name": "Inland Empire"},
        {"code": "losangeles", "name": "Los Angeles"},
        {"code": "mendocino", "name": "Mendocino County"},
        {"code": "merced", "name": "Merced"},
        {"code": "modesto", "name": "Modesto"},
        {"code": "monterey", "name": "Monterey"},
        {"code": "orangecounty", "name": "Orange County"},
        {"code": "palmsprings", "name": "Palm Springs"},
        {"code": "redding", "name": "Redding"},
        {"code": "sacramento", "name": "Sacramento"},
        {"code": "sandiego", "name": "San Diego"},
        {"code": "sfbay", "name": "San Francisco Bay Area"},
        {"code": "slo", "name": "San Luis Obispo"},
        {"code": "santabarbara", "name": "Santa Barbara"},
        {"code": "santamaria", "name": "Santa Maria"},
        {"code": "stockton", "name": "Stockton"},
        {"code": "susanville", "name": "Susanville"},
        {"code": "ventura", "name": "Ventura"},
        {"code": "visalia", "name": "Visalia"},
        {"code": "yubasutter", "name": "Yuba-Sutter"},
    ]},
    "Colorado": {"regions": [
        {"code": "boulder", "name": "Boulder"},
        {"code": "coloradosprings", "name": "Colorado Springs"},
        {"code": "denver", "name": "Denver"},
        {"code": "eastco", "name": "Eastern Colorado"},
        {"code": "fortcollins", "name": "Fort Collins"},
        {"code": "rockies", "name": "Rockies"},
        {"code": "pueblo", "name": "Pueblo"},
        {"code": "westslope", "name": "Western Slope"},
    ]},
    "Connecticut": {"regions": [
        {"code": "newlondon", "name": "New London"},
        {"code": "hartford", "name": "Hartford"},
        {"code": "newhaven", "name": "New Haven"},
    ]},
    "Delaware": {"regions": [
        {"code": "delaware", "name": "Delaware"},
    ]},
    "Florida": {"regions": [
        {"code": "daytona", "name": "Daytona Beach"},
        {"code": "fortlauderdale", "name": "Fort Lauderdale"},
        {"code": "fortmyers", "name": "Fort Myers"},
        {"code": "gainesville", "name": "Gainesville"},
        {"code": "heartland", "name": "Heartland"},
        {"code": "jacksonville", "name": "Jacksonville"},
        {"code": "keys", "name": "Florida Keys"},
        {"code": "lakeland", "name": "Lakeland"},
        {"code": "miami", "name": "Miami"},
        {"code": "ocala", "name": "Ocala"},
        {"code": "orlando", "name": "Orlando"},
        {"code": "panamacity", "name": "Panama City"},
        {"code": "pensacola", "name": "Pensacola"},
        {"code": "sarasota", "name": "Sarasota"},
        {"code": "spacecoast", "name": "Space Coast"},
        {"code": "staugustine", "name": "St. Augustine"},
        {"code": "tallahassee", "name": "Tallahassee"},
        {"code": "tampa", "name": "Tampa"},
        {"code": "treasurecoast", "name": "Treasure Coast"},
    ]},
    "Georgia": {"regions": [
        {"code": "albanyga", "name": "Albany"},
        {"code": "athensga", "name": "Athens"},
        {"code": "atlanta", "name": "Atlanta"},
        {"code": "augusta", "name": "Augusta"},
        {"code": "brunswick", "name": "Brunswick"},
        {"code": "columbusga", "name": "Columbus"},
        {"code": "macon", "name": "Macon"},
        {"code": "nwga", "name": "Northwest Georgia"},
        {"code": "savannah", "name": "Savannah"},
        {"code": "statesboro", "name": "Statesboro"},
        {"code": "valdosta", "name": "Valdosta"},
        {"code": "warnerrobins", "name": "Warner Robins"},
    ]},
    "Hawaii": {"regions": [
        {"code": "honolulu", "name": "Honolulu"},
    ]},
    "Idaho": {"regions": [
        {"code": "boise", "name": "Boise"},
        {"code": "eastidaho", "name": "East Idaho"},
        {"code": "lewiston", "name": "Lewiston"},
        {"code": "twinfalls", "name": "Twin Falls"},
    ]},
    "Illinois": {"regions": [
        {"code": "bn", "name": "Bloomington-Normal"},
        {"code": "chambana", "name": "Champaign-Urbana"},
        {"code": "chicago", "name": "Chicago"},
        {"code": "decatur", "name": "Decatur"},
        {"code": "lasalle", "name": "La Salle"},
        {"code": "mattoon", "name": "Mattoon"},
        {"code": "peoria", "name": "Peoria"},
        {"code": "rockford", "name": "Rockford"},
        {"code": "carbondale", "name": "Carbondale"},
        {"code": "quincy", "name": "Quincy"},
    ]},
    "Indiana": {"regions": [
        {"code": "bloomington", "name": "Bloomington"},
        {"code": "evansville", "name": "Evansville"},
        {"code": "fortwayne", "name": "Fort Wayne"},
        {"code": "indianapolis", "name": "Indianapolis"},
        {"code": "kokomo", "name": "Kokomo"},
        {"code": "muncie", "name": "Muncie"},
        {"code": "richmondin", "name": "Richmond"},
        {"code": "southbend", "name": "South Bend"},
        {"code": "terrehaute", "name": "Terre Haute"},
    ]},
    "Iowa": {"regions": [
        {"code": "ames", "name": "Ames"},
        {"code": "cedarrapids", "name": "Cedar Rapids"},
        {"code": "desmoines", "name": "Des Moines"},
        {"code": "dubuque", "name": "Dubuque"},
        {"code": "fortdodge", "name": "Fort Dodge"},
        {"code": "iowacity", "name": "Iowa City"},
        {"code": "masoncity", "name": "Mason City"},
        {"code": "quadcities", "name": "Quad Cities"},
        {"code": "siouxcity", "name": "Sioux City"},
        {"code": "waterloo", "name": "Waterloo"},
    ]},
    "Kansas": {"regions": [
        {"code": "lawrence", "name": "Lawrence"},
        {"code": "ksu", "name": "Manhattan / KSU"},
        {"code": "nwks", "name": "Northwest Kansas"},
        {"code": "salina", "name": "Salina"},
        {"code": "seks", "name": "Southeast Kansas"},
        {"code": "swks", "name": "Southwest Kansas"},
        {"code": "topeka", "name": "Topeka"},
        {"code": "wichita", "name": "Wichita"},
    ]},
    "Kentucky": {"regions": [
        {"code": "bgky", "name": "Bowling Green"},
        {"code": "eastky", "name": "Eastern Kentucky"},
        {"code": "lexington", "name": "Lexington"},
        {"code": "louisville", "name": "Louisville"},
        {"code": "owensboro", "name": "Owensboro"},
        {"code": "westky", "name": "Western Kentucky"},
    ]},
    "Louisiana": {"regions": [
        {"code": "batonrouge", "name": "Baton Rouge"},
        {"code": "cenla", "name": "Central Louisiana"},
        {"code": "houma", "name": "Houma"},
        {"code": "lafayette", "name": "Lafayette"},
        {"code": "lakecharles", "name": "Lake Charles"},
        {"code": "monroe", "name": "Monroe"},
        {"code": "neworleans", "name": "New Orleans"},
        {"code": "shreveport", "name": "Shreveport"},
    ]},
    "Maine": {"regions": [
        {"code": "maine", "name": "Maine"},
    ]},
    "Maryland": {"regions": [
        {"code": "annapolis", "name": "Annapolis"},
        {"code": "baltimore", "name": "Baltimore"},
        {"code": "easternshore", "name": "Eastern Shore"},
        {"code": "frederick", "name": "Frederick"},
        {"code": "smd", "name": "Southern Maryland"},
    ]},
    "Massachusetts": {"regions": [
        {"code": "boston", "name": "Boston"},
        {"code": "capecod", "name": "Cape Cod"},
        {"code": "southcoast", "name": "South Coast"},
        {"code": "worcester", "name": "Worcester"},
    ]},
    "Michigan": {"regions": [
        {"code": "annarbor", "name": "Ann Arbor"},
        {"code": "battlecreek", "name": "Battle Creek"},
        {"code": "centralmich", "name": "Central Michigan"},
        {"code": "detroit", "name": "Detroit"},
        {"code": "flint", "name": "Flint"},
        {"code": "grandrapids", "name": "Grand Rapids"},
        {"code": "holland", "name": "Holland"},
        {"code": "jxn", "name": "Jackson"},
        {"code": "kalamazoo", "name": "Kalamazoo"},
        {"code": "lansing", "name": "Lansing"},
        {"code": "monroemi", "name": "Monroe"},
        {"code": "muskegon", "name": "Muskegon"},
        {"code": "nmi", "name": "Northern Michigan"},
        {"code": "porthuron", "name": "Port Huron"},
        {"code": "saginaw", "name": "Saginaw"},
        {"code": "swmi", "name": "Southwest Michigan"},
        {"code": "thumb", "name": "The Thumb"},
    ]},
    "Minnesota": {"regions": [
        {"code": "bemidji", "name": "Bemidji"},
        {"code": "brainerd", "name": "Brainerd"},
        {"code": "duluth", "name": "Duluth"},
        {"code": "mankato", "name": "Mankato"},
        {"code": "minneapolis", "name": "Minneapolis / St. Paul"},
        {"code": "rmn", "name": "Rochester"},
        {"code": "stcloud", "name": "St. Cloud"},
    ]},
    "Mississippi": {"regions": [
        {"code": "gulfport", "name": "Gulfport / Biloxi"},
        {"code": "hattiesburg", "name": "Hattiesburg"},
        {"code": "jackson", "name": "Jackson"},
        {"code": "meridian", "name": "Meridian"},
        {"code": "northmiss", "name": "North Mississippi"},
        {"code": "southmiss", "name": "South Mississippi"},
    ]},
    "Missouri": {"regions": [
        {"code": "columbiamo", "name": "Columbia"},
        {"code": "joplin", "name": "Joplin"},
        {"code": "kansascity", "name": "Kansas City"},
        {"code": "kirksville", "name": "Kirksville"},
        {"code": "loz", "name": "Lake of the Ozarks"},
        {"code": "semo", "name": "Southeast Missouri"},
        {"code": "springfield", "name": "Springfield"},
        {"code": "stjoseph", "name": "St. Joseph"},
        {"code": "stlouis", "name": "St. Louis"},
    ]},
    "Montana": {"regions": [
        {"code": "billings", "name": "Billings"},
        {"code": "bozeman", "name": "Bozeman"},
        {"code": "butte", "name": "Butte"},
        {"code": "greatfalls", "name": "Great Falls"},
        {"code": "helena", "name": "Helena"},
        {"code": "kalispell", "name": "Kalispell"},
        {"code": "missoula", "name": "Missoula"},
    ]},
    "Nebraska": {"regions": [
        {"code": "grandisland", "name": "Grand Island"},
        {"code": "lincoln", "name": "Lincoln"},
        {"code": "northplatte", "name": "North Platte"},
        {"code": "omaha", "name": "Omaha"},
        {"code": "scottsbluff", "name": "Scottsbluff"},
    ]},
    "Nevada": {"regions": [
        {"code": "elko", "name": "Elko"},
        {"code": "lasvegas", "name": "Las Vegas"},
        {"code": "reno", "name": "Reno"},
    ]},
    "New Hampshire": {"regions": [
        {"code": "nh", "name": "New Hampshire"},
    ]},
    "New Jersey": {"regions": [
        {"code": "cnj", "name": "Central NJ"},
        {"code": "jerseyshore", "name": "Jersey Shore"},
        {"code": "newjersey", "name": "North NJ"},
        {"code": "southjersey", "name": "South NJ"},
    ]},
    "New Mexico": {"regions": [
        {"code": "albuquerque", "name": "Albuquerque"},
        {"code": "clovis", "name": "Clovis"},
        {"code": "farmington", "name": "Farmington"},
        {"code": "lascruces", "name": "Las Cruces"},
        {"code": "roswell", "name": "Roswell"},
        {"code": "santafe", "name": "Santa Fe"},
    ]},
    "New York": {"regions": [
        {"code": "albany", "name": "Albany"},
        {"code": "binghamton", "name": "Binghamton"},
        {"code": "buffalo", "name": "Buffalo"},
        {"code": "catskills", "name": "Catskills"},
        {"code": "chautauqua", "name": "Chautauqua"},
        {"code": "elmira", "name": "Elmira"},
        {"code": "fingerlakes", "name": "Finger Lakes"},
        {"code": "glensfalls", "name": "Glens Falls"},
        {"code": "hudsonvalley", "name": "Hudson Valley"},
        {"code": "ithaca", "name": "Ithaca"},
        {"code": "longisland", "name": "Long Island"},
        {"code": "newyork", "name": "New York City"},
        {"code": "oneonta", "name": "Oneonta"},
        {"code": "plattsburgh", "name": "Plattsburgh"},
        {"code": "potsdam", "name": "Potsdam"},
        {"code": "rochester", "name": "Rochester"},
        {"code": "syracuse", "name": "Syracuse"},
        {"code": "utica", "name": "Utica"},
        {"code": "watertown", "name": "Watertown"},
    ]},
    "North Carolina": {"regions": [
        {"code": "asheville", "name": "Asheville"},
        {"code": "boone", "name": "Boone"},
        {"code": "charlotte", "name": "Charlotte"},
        {"code": "eastnc", "name": "Eastern NC"},
        {"code": "fayetteville", "name": "Fayetteville"},
        {"code": "greensboro", "name": "Greensboro"},
        {"code": "hickory", "name": "Hickory"},
        {"code": "onslow", "name": "Jacksonville / Onslow"},
        {"code": "outerbanks", "name": "Outer Banks"},
        {"code": "raleigh", "name": "Raleigh"},
        {"code": "wilmington", "name": "Wilmington"},
        {"code": "winstonsalem", "name": "Winston-Salem"},
    ]},
    "North Dakota": {"regions": [
        {"code": "bismarck", "name": "Bismarck"},
        {"code": "fargo", "name": "Fargo"},
        {"code": "grandforks", "name": "Grand Forks"},
        {"code": "nd", "name": "North Dakota (Other)"},
    ]},
    "Ohio": {"regions": [
        {"code": "akroncanton", "name": "Akron / Canton"},
        {"code": "ashtabula", "name": "Ashtabula"},
        {"code": "athensohio", "name": "Athens"},
        {"code": "chillicothe", "name": "Chillicothe"},
        {"code": "cincinnati", "name": "Cincinnati"},
        {"code": "cleveland", "name": "Cleveland"},
        {"code": "columbus", "name": "Columbus"},
        {"code": "dayton", "name": "Dayton"},
        {"code": "limaohio", "name": "Lima"},
        {"code": "mansfield", "name": "Mansfield"},
        {"code": "sandusky", "name": "Sandusky"},
        {"code": "toledo", "name": "Toledo"},
        {"code": "tuscarawas", "name": "Tuscarawas County"},
        {"code": "youngstown", "name": "Youngstown"},
        {"code": "zanesville", "name": "Zanesville"},
    ]},
    "Oklahoma": {"regions": [
        {"code": "lawton", "name": "Lawton"},
        {"code": "enid", "name": "Enid"},
        {"code": "oklahomacity", "name": "Oklahoma City"},
        {"code": "stillwater", "name": "Stillwater"},
        {"code": "tulsa", "name": "Tulsa"},
    ]},
    "Oregon": {"regions": [
        {"code": "bend", "name": "Bend"},
        {"code": "corvallis", "name": "Corvallis"},
        {"code": "eastoregon", "name": "Eastern Oregon"},
        {"code": "eugene", "name": "Eugene"},
        {"code": "klamath", "name": "Klamath Falls"},
        {"code": "medford", "name": "Medford"},
        {"code": "oregoncoast", "name": "Oregon Coast"},
        {"code": "portland", "name": "Portland"},
        {"code": "roseburg", "name": "Roseburg"},
        {"code": "salem", "name": "Salem"},
    ]},
    "Pennsylvania": {"regions": [
        {"code": "altoona", "name": "Altoona"},
        {"code": "chambersburg", "name": "Chambersburg"},
        {"code": "erie", "name": "Erie"},
        {"code": "harrisburg", "name": "Harrisburg"},
        {"code": "lancaster", "name": "Lancaster"},
        {"code": "allentown", "name": "Lehigh Valley"},
        {"code": "meadville", "name": "Meadville"},
        {"code": "philadelphia", "name": "Philadelphia"},
        {"code": "pittsburgh", "name": "Pittsburgh"},
        {"code": "poconos", "name": "Poconos"},
        {"code": "reading", "name": "Reading"},
        {"code": "scranton", "name": "Scranton"},
        {"code": "pennstate", "name": "State College"},
        {"code": "williamsport", "name": "Williamsport"},
        {"code": "york", "name": "York"},
    ]},
    "Rhode Island": {"regions": [
        {"code": "providence", "name": "Providence"},
    ]},
    "South Carolina": {"regions": [
        {"code": "charleston", "name": "Charleston"},
        {"code": "columbia", "name": "Columbia"},
        {"code": "florencesc", "name": "Florence"},
        {"code": "greenville", "name": "Greenville"},
        {"code": "hiltonhead", "name": "Hilton Head"},
        {"code": "myrtlebeach", "name": "Myrtle Beach"},
    ]},
    "South Dakota": {"regions": [
        {"code": "nesd", "name": "Northeast SD"},
        {"code": "rapidcity", "name": "Rapid City"},
        {"code": "siouxfalls", "name": "Sioux Falls"},
        {"code": "sd", "name": "South Dakota (Other)"},
    ]},
    "Tennessee": {"regions": [
        {"code": "chattanooga", "name": "Chattanooga"},
        {"code": "clarksville", "name": "Clarksville"},
        {"code": "cookeville", "name": "Cookeville"},
        {"code": "jackson", "name": "Jackson"},
        {"code": "knoxville", "name": "Knoxville"},
        {"code": "memphis", "name": "Memphis"},
        {"code": "nashville", "name": "Nashville"},
        {"code": "tricities", "name": "Tri-Cities"},
    ]},
    "Texas": {"regions": []},
    "Utah": {"regions": []},
    "Vermont": {"regions": []},
    "Virginia": {"regions": []},
    "Washington": {"regions": []},
    "West Virginia": {"regions": [
        {"code": "charlestonwv", "name": "Charleston"},
        {"code": "martinsburg", "name": "Eastern Panhandle"},
        {"code": "huntington", "name": "Huntington"},
        {"code": "parkersburg", "name": "Parkersburg"},
    ]},
    "Wisconsin": {"regions": []},
    "Wyoming": {"regions": []},

}