# Generated by Django 6.0.1 on 2026-02-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_scraperun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelead',
            old_name='description',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='servicelead',
            old_name='source_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='servicelead',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='servicelead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='servicelead',
            name='service_type',
        ),
        migrations.AddField(
            model_name='servicelead',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='map_accuracy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
