# Generated by Django 6.0.1 on 2026-02-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_servicelead_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
