# Generated by Django 6.0.1 on 2026-02-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_servicelead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperun',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='scraperun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='leads_collected',
            field=models.IntegerField(default=0),
        ),
    ]
