# Generated by Django 6.0.1 on 2026-02-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_created_at_scraperun_started_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperun',
            old_name='started_at',
            new_name='created_at',
        ),
    ]
