# Generated by Django 6.0.1 on 2026-02-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_started_at_scraperun_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelead',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='score_reason',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
