# Generated by Django 6.0.1 on 2026-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_servicelead_score_servicelead_score_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['post_id'], name='base_servic_post_id_61a69a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['created_at'], name='base_servic_created_62e73e_idx'),
        ),
    ]
