# Generated by Django 6.0.1 on 2026-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_servicelead_base_servic_post_id_61a69a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelead',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
