# Generated by Django 6.0.1 on 2026-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_servicelead_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelead',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['content_hash'], name='base_servic_content_21d6d5_idx'),
        ),
    ]
