# Generated by Django 6.0.1 on 2026-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_servicelead_content_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraperun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scraperun',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='leads_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='location_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='location_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='location_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='service_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='source',
            field=models.CharField(choices=[('CRAIGSLIST', 'Craigslist'), ('FACEBOOK', 'Facebook')], default='CRAIGSLIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='scraperun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='RUNNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicelead',
            name='post_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicelead',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['source'], name='base_servic_source_10e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['service_category'], name='base_servic_service_79c123_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['score'], name='base_servic_score_027cc1_idx'),
        ),
    ]
