# Generated by Django 6.0.1 on 2026-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_scraperun_options_scraperun_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='current_stage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='stage_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
