# Generated by Django 6.0.1 on 2026-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_scraperun_activity_log_scraperun_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='apify_run_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
