# Generated by Django 6.0.1 on 2026-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_scraperun_apify_run_ids_scraperun_cancel_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelead',
            name='fb_group_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='fb_group_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['fb_group_name'], name='base_servic_fb_grou_382026_idx'),
        ),
    ]
