# Generated by Django 6.0.1 on 2026-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_servicelead_fb_group_name_servicelead_fb_group_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedFbGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=500)),
                ('post_count', models.IntegerField(default=0)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('first_scraped', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_scraped'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedFbPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('group_url', models.URLField(blank=True, db_index=True, max_length=1000)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.AddField(
            model_name='scraperun',
            name='max_posts_per_group',
            field=models.IntegerField(default=50),
        ),
    ]
