# Generated by Django 6.0.1 on 2026-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_scrapedfbgroup_scrapedfbpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='google_deep_scrape',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='google_max_pages',
            field=models.IntegerField(default=3),
        ),
    ]
