# Generated by Django 6.0.1 on 2026-03-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_scraperun_google_deep_scrape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='source_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
