# Generated by Django 6.0.3 on 2026-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_scraperun_source_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='limit_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='max_leads',
            field=models.IntegerField(default=0),
        ),
    ]
