# Generated by Django 6.0.3 on 2026-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_scraperun_limit_stop_scraperun_max_leads'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['title'], name='base_servic_title_b816a3_idx'),
        ),
    ]
