# Generated by Django 6.0.3 on 2026-04-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_servicelead_base_servic_title_b816a3_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicelead',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__isnull', False), models.Q(('content_hash', ''), _negated=True)), fields=('content_hash',), name='unique_content_hash_nonempty'),
        ),
    ]
