# Generated by Django 6.0.3 on 2026-04-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_servicelead_unique_content_hash_nonempty'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelead',
            name='title_ngram_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
