# Generated by Django 6.0.1 on 2026-02-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapeSession',
        ),
    ]
